name: Build Kivy Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk unzip wget
          pip install --upgrade pip setuptools
          pip install buildozer cython

      - name: Accept Android Licenses and Install Build Tools
        run: |
          # Create Android SDK directory and download command-line tools
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          
          # Unzip into a temporary folder
          mkdir -p cmdline-tools-temp
          unzip cmdline-tools.zip -d cmdline-tools-temp
          
          # Create the final folder and move files (avoid moving folder into itself)
          mkdir -p cmdline-tools/latest
          mv cmdline-tools-temp/cmdline-tools/* cmdline-tools/latest
          rm -rf cmdline-tools-temp
          
          # Set environment variables so sdkmanager is available
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          
          # Automatically accept all Android SDK licenses
          yes | sdkmanager --licenses
          
          # Install a stable Build Tools version (33.0.0) with accepted licenses
          sdkmanager --install "build-tools;33.0.0"

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: ./.github/actions/local-upload-artifact
        with:
          name: KivyToDoList-APK
          path: bin/*.apk
