name: Build Kivy Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository (pinned commit SHA for actions/checkout@v3)
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      # 2. Set up Python (pinned commit SHA for actions/setup-python@v3)
      - name: Set up Python
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566
        with:
          python-version: "3.9"

      # 3. Install dependencies (Ubuntu packages + Buildozer + Cython)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk unzip
          pip install --upgrade pip setuptools
          pip install buildozer cython

      # 4. Build your APK
      - name: Build APK
        run: buildozer -v android debug

      # 5. Upload APK (pinned commit SHA for actions/upload-artifact@v3)
      - name: Upload APK
        uses: actions/upload-artifact@85a60353e1640fbe0b07b3dba17c51d310d3170c
        with:
          name: KivyToDoList-APK
          path: bin/*.apk
