name: Build Kivy Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk unzip wget
          pip install --upgrade pip setuptools
          pip install buildozer cython

      - name: Accept Licenses & Install Build-Tools 36
        run: |
          # 1) Create an Android SDK folder
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          
          # 2) Download the command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          
          # 3) Unzip into a temporary folder
          mkdir -p cmdline-tools-temp
          unzip cmdline-tools.zip -d cmdline-tools-temp
          
          # 4) Move them into cmdline-tools/latest
          mkdir -p cmdline-tools/latest
          mv cmdline-tools-temp/cmdline-tools/* cmdline-tools/latest
          rm -rf cmdline-tools-temp
          
          # 5) Expose sdkmanager in our PATH
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          
          # 6) Update the SDK (check for new packages)
          yes | sdkmanager --update
          
          # 7) Force-install Build-Tools 36.0.0 & platform 36 from the canary channel
          #    If "platforms;android-36" doesn't exist, sdkmanager will skip it, but let's attempt it anyway
          yes | sdkmanager --channel=3 --install "platform-tools" "platforms;android-36" "build-tools;36.0.0"
          
          # 8) Accept leftover licenses (if any)
          yes | sdkmanager --licenses

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        # If you vendor 'upload-artifact' locally, keep the local path:
        # uses: ./.github/actions/local-upload-artifact
        # Otherwise, if your org/repo allows Marketplace actions, use:
        # uses: actions/upload-artifact@v3
        uses: ./.github/actions/local-upload-artifact
        with:
          name: KivyToDoList-APK
          path: bin/*.apk
