name: Build Kivy Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk unzip
          pip install --upgrade pip setuptools
          pip install buildozer cython

      - name: Accept Android Licenses
        run: |
          # Install command-line tools
          sudo apt-get update
          sudo apt-get install -y wget
          
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          
          # Download the command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          
          # Unzip into a new folder called "cmdline-tools"
          mkdir -p cmdline-tools
          unzip cmdline-tools.zip -d cmdline-tools
          
          # The extracted zip also contains a "cmdline-tools" folder, so we move its contents into "cmdline-tools/latest"
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest
          
          # Export environment variables so sdkmanager is recognized
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          
          # Accept licenses automatically
          yes | sdkmanager --licenses


      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: ./.github/actions/local-upload-artifact
        with:
          name: KivyToDoList-APK
          path: bin/*.apk
