name: Build Kivy Android APK

on: 
  push:
    branches:
      - main  # Runs when you push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # Uses Ubuntu runner (required for Buildozer)
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk unzip
        pip install --upgrade pip setuptools
        pip install buildozer cython

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: KivyToDoList-APK
        path: bin/*.apk  # Uploads the APK file as an artifact
